config/routes.rb
Lists::Application.routes.draw do

  match '/auth/:provider/create/:uid/:token' => 'authentications#create'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/:provider/:id', :to => 'authentications#sign_in_existing', :constraints => {:id => /\d+/}
  match '/auth/failure' => 'authentications#failure'
  match '/authentications/:provider/:id/business/:business_id' => 'authentications#business', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/friends' => 'authentications#friends', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/checkins' => 'authentications#checkins', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/full_profile' => 'authentications#full_profile', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/user' => 'authentications#user', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/checkins/likes' => 'authentications#likes_from_checkins', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/likes' => 'authentications#likes', :constraints => {:id => /\d+/}

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}, :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  resources :authentications

  root :to => "application#index"

  resources :images do
    collection do
      get :image_download
      post :image_upload
      post :save
      get :crop
    end
  end

    namespace "admin" do
      resources :users do
        get :dashboard, :on => :collection
      end
      resources :businesses do
        get :dashboard, :on => :collection
        get :geo, :on => :collection
        get :edit, :on => :member
      end

    end

    resources :user do
      resources :likes
      resources :trys
      resources :friend_lists

      resources :user_purchases do
        member do
	        get :purchase
	        post :purchase
	        get :purchase_test
	        get :complete
	        post :complete
	        get :purchase_callback
	        post :purchase_callback
	        get :cancel_callback
	        post :cancel_callback
	        get :refund
	        post :refund
	        get :refund_complete
	        post :refund_complete
	        get :refund_callback
	        post :refund_callback
	        get :cancel_refund_callback
	        post :cancel_refund_callback
        end
      end

      resources :lists do
        resources :comments
        get :manage, :on => :collection
      end
      resources :transaction_terms
      resources :images

    end

      resources :user_purchases do
        member do
	        get :purchase
	        post :purchase
	        get :purchase_test
	        get :complete
	        post :complete
	        get :purchase_callback
	        post :purchase_callback
	        get :cancel_callback
	        post :cancel_callback
	        get :refund
	        post :refund
	        get :refund_complete
	        post :refund_complete
	        get :refund_callback
	        post :refund_callback
	        get :cancel_refund_callback
	        post :cancel_refund_callback
        end
      end

      resources :cities do
        resources :social_coupons
          resources :businesses do
            resources :likes
            resources :trys

            resources :social_coupons do
              get :sold, :on => :collection
              get :reserved, :on => :collection
              get :top_ten, :on => :collection
           end
          get :recent_activity, :on => :member
        end
        resources :user
      end

  resources :businesses do
    collection do
      get :dashboard
      get :geo
    end

    member do
      post :set_business_website
      get :edit
    end

    resources :likes
    resources :trys
    resources :promo_messages

    resources :social_coupons do
      member do
        get :details
        get :check_status
        get :campaign_overview
        get :campaign_details
        get :auto_complete_for_business_name
        get :auto_complete_for_city_name
      end
      collection do
        get :deal_cities
        get :deal_of_the_day
        get :deals_of_the_day
        get :payout_report
      end
    end

  end

  resources :social_coupons do
      member do
        get :details
        get :check_status
        get :campaign_overview
        get :campaign_details
        get :auto_complete_for_business_name
        get :auto_complete_for_city_name
        get :payout_report
      end
      collection do
        get :deal_cities
        get :deal_of_the_day
        get :deals_of_the_day
        get :payout_report
      end
  end

  match 'social_coupons/:id/email_template/:template' => 'social_coupons#email_template'

  resources :coupons

  match 'payment_transactions_coordinator/duplicates_needing_refunds' => 'payment_transactions_coordinator#duplicates_needing_refunds'

  resources :user_purchases do
    member do
      get :purchase
      post :purchase
      get :purchase_test
      get :complete
      post :complete
      get :purchase_callback
      post :purchase_callback
      get :cancel_callback
      post :cancel_callback
      get :refund
      post :refund
      get :refund_complete
      post :refund_complete
      get :refund_callback
      post :refund_callback
      get :cancel_refund_callback
      post :cancel_refund_callback
    end
  end

  match ':controller(/:action(/:id(.:format)))'
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base

  set_table_name "tbl_business_types"
  set_primary_key :business_type_id
  
  has_many :businesses

  def id
    business_type_id
  end

  def business_type_path_parsed
	  business_type_path.split('/').pop(2).join(', ')
  end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  layout 'avatar_editor'
  in_place_edit_for :business, :website

  def dashboard
    page = params['page'] || 1
    @businesses = Business.find_top_ranked_businesses_without_pictures page
    @details = Business.get_details_for_list_of_business_ids @businesses
  end

  def edit
    @business = Business.find(params[:id])
  end

  def geo
    page = params['page'] || 1
    @zip_code_list = CHICAGO
    @details = Business.find_all_businesses_in_zip page, @zip_code_list
  end


end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business_details.html.erb
<tr>
  <div class="business_listing">

      <a href="<%="/businesses/#{business.business_id}/edit"%>">
        <%if business.default_image_file_path.present? %>
          <%= image_tag "#{AppConf.image_server}#{AppConf.image_url}#{AppConf.image_path_square100}#{business.default_image_file_path}", :class=>"photo" %>
        <% else %>
          <div class="photo">NO IMAGE</div>
        <% end %>
      </a>
      <p><a target="_blank" href="<%="#{AppConf.image_server}/business/business-#{business.business_id}"%>"><%= h business.business_name %></a> </p>
    <p><%= h business.like_count %> likes</p>
      <% @business = business %>
      <p><%= in_place_editor_field :business, "website" %></p>
    </div>

</tr>

app/views/businesses/dashboard.html.erb
<% title "All Liked Businesses, by like count" %>



<% for biz in @details %>
    <%= render :partial => 'business_details', :locals => {:business => biz} %>
<% end %>
<%= will_paginate @businesses %>

app/views/businesses/edit.html.erb
<h1>
  <%= image_tag "#{AppConf.image_server}#{AppConf.image_url}#{AppConf.image_path_square100}#{@business.default_image_file_path}", :id => "default_img" %>
  
  <%= @business.business_name %>
</h1>

<%= in_place_editor_field :business, "website"%>

<script language="JavaScript">


</script>

<div id="img_block">
  <p>Upload an image</p>
  <% form_tag({:controller=>'images', :action => 'image_upload'},
               :multipart => true) do %>
      <%= hidden_field_tag "id", "#{@business.business_id}" %>
      <p><label for="upload_file">Select File</label> :
        <%= file_field 'upload', 'datafile' %></p>
      <%= submit_tag "Upload" %>
  <% end %>
</div>

<div id="img_block">

  <p>Google images for  <%= @business.business_name %> </p>

  <% @business.google_images.each do |image| %>
      <a href=<%= image_download_images_url(:id=>@business.business_id, :image=>image) %>>
        <img id="thumbnail" src=<%= "'#{image}'" %>/>
      </a>
  <% end %>

</div>

<div id="img_block">

  <p>images from company website (<a target=_blank href="<%= @business.canonicalized_website %>"><%= @business.website %></a>)</p>

  <% @business.images.each do |image| %>
      <a href=<%= image_download_images_url(:id=>@business.business_id, :image=>image) %>>
        <img id="thumbnail" src=<%= "'#{image}'" %>/>
      </a>
  <% end %>

</div>

<p>
  <%= link_to "View All", '/businesses/dashboard' %>
</p>

app/views/businesses/geo.html.erb
<% title "All Businesses in a region, by like count" %>

<p>Businesses in the following zip codes <%= @zip_code_list%> </p>



<% for biz in @details %>
    <%= render :partial => 'business_details', :locals => {:business => biz} %>
<% end %>
<%= will_paginate @details %>