config/routes.rb
Lists::Application.routes.draw do

  match '/auth/:provider/create/:uid/:token' => 'authentications#create'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/:provider/:id', :to => 'authentications#sign_in_existing', :constraints => {:id => /\d+/}
  match '/auth/failure' => 'authentications#failure'
  match '/authentications/:provider/:id/business/:business_id' => 'authentications#business', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/friends' => 'authentications#friends', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/checkins' => 'authentications#checkins', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/full_profile' => 'authentications#full_profile', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/user' => 'authentications#user', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/checkins/likes' => 'authentications#likes_from_checkins', :constraints => {:id => /\d+/}
  match '/authentications/:provider/:id/likes' => 'authentications#likes', :constraints => {:id => /\d+/}

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}, :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  resources :authentications

  root :to => "application#index"

  resources :images do
    collection do
      get :image_download
      post :image_upload
      post :save
      get :crop
    end
  end

    namespace "admin" do
      resources :users do
        get :dashboard, :on => :collection
      end
      resources :businesses do
        get :dashboard, :on => :collection
        get :geo, :on => :collection
        get :edit, :on => :member
      end

    end

    resources :user do
      resources :likes
      resources :trys
      resources :friend_lists

      resources :user_purchases do
        member do
	        get :purchase
	        post :purchase
	        get :purchase_test
	        get :complete
	        post :complete
	        get :purchase_callback
	        post :purchase_callback
	        get :cancel_callback
	        post :cancel_callback
	        get :refund
	        post :refund
	        get :refund_complete
	        post :refund_complete
	        get :refund_callback
	        post :refund_callback
	        get :cancel_refund_callback
	        post :cancel_refund_callback
        end
      end

      resources :lists do
        resources :comments
        get :manage, :on => :collection
      end
      resources :transaction_terms
      resources :images

    end

      resources :user_purchases do
        member do
	        get :purchase
	        post :purchase
	        get :purchase_test
	        get :complete
	        post :complete
	        get :purchase_callback
	        post :purchase_callback
	        get :cancel_callback
	        post :cancel_callback
	        get :refund
	        post :refund
	        get :refund_complete
	        post :refund_complete
	        get :refund_callback
	        post :refund_callback
	        get :cancel_refund_callback
	        post :cancel_refund_callback
        end
      end

      resources :cities do
        resources :social_coupons
          resources :businesses do
            resources :likes
            resources :trys

            resources :social_coupons do
              get :sold, :on => :collection
              get :reserved, :on => :collection
              get :top_ten, :on => :collection
           end
          get :recent_activity, :on => :member
        end
        resources :user
      end

  resources :businesses do
    collection do
      get :dashboard
      get :geo
    end

    member do
      post :set_business_website
      get :edit
    end

    resources :likes
    resources :trys
    resources :promo_messages

    resources :social_coupons do
      member do
        get :details
        get :check_status
        get :campaign_overview
        get :campaign_details
        get :auto_complete_for_business_name
        get :auto_complete_for_city_name
      end
      collection do
        get :deal_cities
        get :deal_of_the_day
        get :deals_of_the_day
        get :payout_report
      end
    end

  end

  resources :social_coupons do
      member do
        get :details
        get :check_status
        get :campaign_overview
        get :campaign_details
        get :auto_complete_for_business_name
        get :auto_complete_for_city_name
        get :payout_report
      end
      collection do
        get :deal_cities
        get :deal_of_the_day
        get :deals_of_the_day
        get :payout_report
      end
  end

  match 'social_coupons/:id/email_template/:template' => 'social_coupons#email_template'

  resources :coupons

  match 'payment_transactions_coordinator/duplicates_needing_refunds' => 'payment_transactions_coordinator#duplicates_needing_refunds'

  resources :user_purchases do
    member do
      get :purchase
      post :purchase
      get :purchase_test
      get :complete
      post :complete
      get :purchase_callback
      post :purchase_callback
      get :cancel_callback
      post :cancel_callback
      get :refund
      post :refund
      get :refund_complete
      post :refund_complete
      get :refund_callback
      post :refund_callback
      get :cancel_refund_callback
      post :cancel_refund_callback
    end
  end

  match ':controller(/:action(/:id(.:format)))'
end

app/models/transaction_term.rb
class TransactionTerm < ActiveRecord::Base
  belongs_to :promo_message

  validates_presence_of :terms, :effective_start_date, :effective_end_date

  def effective_start_date
    read_attribute(:effective_start_date).blank? ? Time.now : read_attribute(:effective_start_date)
  end

  def effective_start_date=(value)
    if !value.blank?
      value = value.to_time.in_time_zone(Lists::Application.config.time_zone).beginning_of_day
    end
    write_attribute(:effective_start_date, value)
  end

  def effective_end_date
    read_attribute(:effective_end_date).blank? ? Time.now : read_attribute(:effective_end_date)
  end

  def effective_end_date=(value)
    if !value.blank?
      value = value.to_time.in_time_zone(Lists::Application.config.time_zone).end_of_day
    end
    write_attribute(:effective_end_date, value)
  end
end

app/controllers/transaction_terms_controller.rb
class TransactionTermsController < ApplicationController
  # GET /transaction_terms
  # GET /transaction_terms.xml
  def index
    @transaction_terms = TransactionTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transaction_terms }
    end
  end

  # GET /transaction_terms/1
  # GET /transaction_terms/1.xml
  def show
    @transaction_term = TransactionTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction_term }
    end
  end

  # GET /transaction_terms/new
  # GET /transaction_terms/new.xml
  def new
    @transaction_term = TransactionTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction_term }
    end
  end

  # GET /transaction_terms/1/edit
  def edit
    @transaction_term = TransactionTerm.find(params[:id])
  end

  # POST /transaction_terms
  # POST /transaction_terms.xml
  def create
    @transaction_term = TransactionTerm.new(params[:transaction_term])

    respond_to do |format|
      if @transaction_term.save
        format.html { redirect_to(@transaction_term, :notice => 'Transaction terms was successfully created.') }
        format.xml  { render :xml => @transaction_term, :status => :created, :location => @transaction_term }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction_term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transaction_terms/1
  # PUT /transaction_terms/1.xml
  def update
    @transaction_term = TransactionTerm.find(params[:id])

    respond_to do |format|
      if @transaction_term.update_attributes(params[:transaction_term])
        format.html { redirect_to(@transaction_term, :notice => 'Transaction terms was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction_term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_terms/1
  # DELETE /transaction_terms/1.xml
  def destroy
    @transaction_term = TransactionTerm.find(params[:id])
    @transaction_term.destroy

    respond_to do |format|
      format.html { redirect_to(transaction_terms_index_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/transaction_terms/_form.html.erb
<%= form_for(@transaction_term) do |f| %>
  <% if @transaction_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction_term.errors.count, "error") %> prohibited this transaction_term from being saved:</h2>

      <ul>
      <% @transaction_term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :terms %> <%= f.text_area :terms %><br />

    <%= f.label :effective_start_date %> <%= f.date_select :effective_start_date %><br />
    <%= f.label :effective_end_date %> <%= f.date_select :effective_end_date %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaction_terms/edit.html.erb
<h1>Editing transaction_term</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction_term %> |
<%= link_to 'Back', transaction_terms_index_path %>

app/views/transaction_terms/index.html.erb
<h1>Listing transaction_terms</h1>

<table>
  <tr>
    <th>Terms</th>
    <th>effective date</th>
    <th>end date</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transaction_terms.each do |transaction_term| %>
  <tr>
    <td><%= transaction_term.terms %></td>
    <td><%= transaction_term.effective_start_date %></td>
    <td><%= transaction_term.effective_end_date %></td>
    <td><%= link_to 'Show', transaction_term %></td>
    <td><%= link_to 'Edit', edit_transaction_term_path(transaction_term) %></td>
    <td><%= link_to 'Destroy', transaction_term, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction terms', new_transaction_term_path %>

app/views/transaction_terms/new.html.erb
<h1>New transaction_term</h1>

<%= render 'form' %>

<%= link_to 'Back', transaction_terms_index_path %>

app/views/transaction_terms/show.html.erb
<p id="notice"><%= notice %></p>

terms: <%= @transaction_term.terms %><br />

effective_start_date: <%= @transaction_term.effective_start_date %><br />
effective_end_date: <%= @transaction_term.effective_end_date %><br />

<%= link_to 'Edit', edit_transaction_term_path(@transaction_term) %> |
<%= link_to 'Back', transaction_terms_index_path %>